version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase for Ec2Ami project
      - mvn clean package
  post_build:
    commands:
      - echo Build completed OK (phew !!)
artifacts:
  files:
    - target/Ec2Ami.jar
  discard-paths: yes
